name: deploy blog backend

on: 
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4 # 签出 $GITHUB_WORKSPACE 下的存储库，以便工作流可以访问它
    
    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.18.0

    - name: Install dependencies
      run: |
        npm ci --only=production

    - name: Copy files via SSH
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "./middleware,./route,./service,./utils,./index.js,./package.json"
        target: /var/local/my-blog/server/

    - name: manage backend with pm2
      run: |
        pm2 startOrReload myblog
        pm2 save
